config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :movies
  root to:"movies#index"

  get 'moviesdash', to: 'movies#moviesdash'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/day.rb
class Day
  include Mongoid::Document
  field :dateShow, type: Date
  #Relation
  belongs_to :movie
  has_many :reservations
end

app/models/movie.rb
class Movie
  include Mongoid::Document
  field :name,          type: String
  field :description,   type: String
  field :url_image,     type: String
  field :premiere,      type: Date
  field :dayshow,          type: Integer, default:1
  #relation
  has_many :days
end

app/models/reservation.rb
class Reservation
  include Mongoid::Document
  field :phone, type: String
  field :email, type: String
  field :name, type: String
  field :nid, type: String
  #RELATIONS
  belongs_to :day
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def moviesdash #Sin usar

    if params[:date].empty? then
      date=Date.today
    else
      date=params[:date].to_date
    end
    daysmovies=Day.where(:dateShow=>date)
    movies=[]
    daysmovies.each do |day|
      movies.push(day_id:day.id.to_str,url_image:day.movie.url_image)
    end
    respond_to do |format|
      format.json {render json: movies,  status: 200}
    end
  end

  def index
    @movies = Movie.all
    @movie = Movie.new
    @reservation = Reservation.new
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        fecha=@movie.premiere
        @movie.dayshow.times do |i|
          @movie.days.create! dateShow:fecha
          fecha+=1.day
        end
        format.html { redirect_to @movie, notice: 'La Pélicula ha sido creada!.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:name, :description, :url_image, :dayshow, :premiere)
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    day=Day.find(params[:day_id] )
    respond_to do |format|
      if day.reservations.count< 10 then
        @reservation=day.reservations.create! :name =>params[:name], :phone =>params[:phone], :email=>params[:email], :nid=>params[:nit]
        format.html { redirect_to @reservation, notice: "Reserva creada para la pélicula #{day.movie.name}" }
      else
        @movies = Movie.all
        format.html { redirect_to movies_path , flash: {alert: "No hay cupos disponibles para la pélicula #{day.movie.name} el día #{day.dateShow}"}}
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.require(:reservation).permit(:phone, :email, :name, :nid, :day_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/layouts/_error_form_messages.html.erb
<% if target.errors.any? %>
    <div class="error_explanation">
      <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h4><i class="icon fa fa-ban"></i> ALERTA! <%= pluralize(target.errors.count, "ERROR") %> PROHIBIÓ GUARDAR ESTE REGISTRO:</h4>
        <ul>
          <% target.errors.full_messages.each do |message| %>
          <li><%= message %></li>
      <% end %>
      </ul>
     </div>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html style="font-family: 'Montserrat', sans-serif !important;">
  <head>
    <title>Placeit360</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="skin-blue sidebar-mini">
      <div class="wrapper">
        <header class="main-header">
        <a href="/" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini">M</span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><b>Place</b>it</span>
        </a>
      </header>
      <aside class="main-sidebar">
        <section class="sidebar">
          <ul class="sidebar-menu" data-widget="tree">
            <li><a href="/reservations" class="acustom"><i class="far fa-calendar-alt"></i> <span>Reservas</span></a></li>
            <li><a href="/movies" class="acustom"><i class="fas fa-film"></i> <span>Películas</span></a></li>
          </ul>
        </section>
      </aside>
        <div class="content-wrapper conmovie">
          <% flash.each do |key, value| %>
            <% if key==:alert || key=="alert"; then ; cssx="alert" ; textoalerta="Alerta!" ; fonta="ban"; else ; cssx="info" ; textoalerta="Información"; fonta="thumbs-up"; end  %>
            <div class="alertcls alertcls-<%= cssx %> alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4><i class="icon fa fa-<%= fonta %>"></i> <%= textoalerta %></h4>
                <%= value %>
            </div>
            <% end %>
            <%= yield %>
        </div>
      </div>
  </body>
</html>

app/views/movies/_form.html.erb
<section class="content">
  <div class="box box-default">
    <div class="box-header">
      <h1><b>Película</b></h1>
    </div>
    <div class="box-body">
      <%= form_with(model: movie, local: true) do |form| %>
      <%= render "layouts/error_form_messages", :target => @movie %>
      <div class="row">
        <div class="form-group col-sm-3">
          <%= form.label :name, "Título" %>
          <%= form.text_field :name, class: "form-control", :required => true %>
        </div>
        <div class="form-group col-sm-2">
          <%= form.label :url_image, "Poster URL" %>
          <%= form.text_field :url_image, class: "form-control", :required => true  %>
        </div>
        <div class="form-group col-sm-1">
          <%= form.label :days, "Fechas"%>
          <%= form.number_field :days, class: "form-control", :required => true  %>
        </div>
      </div>
      <div class="row">
        <div class="form-group col-sm-6">
          <%= form.label :description,"Sinopsis" %>
          <%= form.text_area :description, class: "form-control", rows: "3", :required => true  %>
        </div>
      </div>
      <div class="box-footer">
        <%= form.submit "Guardar", class: "btn btn-lg btn-info" %>
      </div>
    <% end %>
  </div>
</div>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<link rel="stylesheet" type="text/css" href="/assets/jquery.dataTables.min.css">
<script type="text/javascript" charset="utf8" src="/assets/jquery.dataTables.min.js"></script>
<div class="box box-default">

  <div class="box-header">
    <h1>Péliculas</h1>
    <div class="select">
      <div class="row">
        <div class="col-sm-7 form-group">
          <h4>Seleccionar Fecha</h4>
          <div class="input-group selectdate">

            <div class="input-group-addon has-default">
              <i class="fas fa-calendar-day"></i>
            </div>
            <div class="form-group has-default">
              <input type="text" class="form-control pull-right" id="dateshowprac">
            </div>
          </div>
        </div>
      </div>

    </div>
    <div class="box-tools pull-right">
      <button type="button" class="btn btn-info btn-lg btncustom" data-toggle="modal" data-target="#modal-newmovie"><i class="fas fa-plus"></i> Crear Nueva Pélicula</button>
    </div>
  </div>
  <div class="box-body">
    <div class="" id="vueapp">
      <div class="containerimage" v-for="movie in lists">
        <img v-bind:src="movie.url_image" class="image">
        <div class="middle">
          <button type="button" class="btn btn-info btncustom" data-toggle="modal" data-target="#modal-reservemovie" v-on:click="asignarmovieid(movie.day_id)">Reservar</button>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- MODAL reservar -->
<div class="modal fade-in" id="modal-reservemovie">
  <div class="modal-dialog modal-SM">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
         <span aria-hidden="true">&times;</span>
       </button>
         <h3 class="modal-title" id="exampleModalLabel">Reservar</h3>
      </div>
      <%= form_with(model: @reservation, local: true) do |form| %>
      <div class="modal-body">

        <div class="row">
          <div class="form-group col-md-6">
            <%= label_tag :name,"Nombre Completo" %>
            <%= text_field_tag :name, "", class: "form-control", required: true %>
          </div>
          <div class="form-group col-md-6">
            <%= label_tag :phone,"Celular" %>
            <%= text_field_tag :phone, "", class: "form-control", required: true %>
          </div>
        </div>
        <div class="row">
          <div class="form-group col-md-6">
            <%= label_tag :nit,"Cédula" %>
            <%= text_field_tag :nit, "", class: "form-control", required: true %>
          </div>
          <div class="form-group col-md-6">
            <%= label_tag :email,"Correo Eléctronico" %>
            <%= text_field_tag :email, "", class: "form-control", required: true %>
          </div>
        </div>
        <div class="form-group">
          <%= hidden_field_tag :day_id%>
        </div>
      </div>
      <div class="modal-footer">
        <div class="actions">
          <%= submit_tag "Reservar Ahora",class: "btn btn-info btncustom float-right"%>
        </div>
      </div>
      <% end  %>
      </div>
    </div>
</div>
<!-- newmovie -->
<div class="modal fade-in" id="modal-newmovie">
  <div class="modal-dialog modal-SM">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
         <span aria-hidden="true">&times;</span>
       </button>
         <h3 class="modal-title" id="exampleModalLabel">Crear Pélicula</h3>
      </div>
        <%= form_with(model: @movie, local: true) do |form| %>
        <div class="modal-body">
          <div class="form-group ">
            <%= form.label :name, "Título" %>
            <%= form.text_field :name, class: "form-control", :required => true %>
          </div>
          <div class="form-group">
            <%= form.label :description,"Sinopsis" %>
            <%= form.text_area :description, class: "form-control", rows: "3", :required => true  %>
          </div>
          <div class="form-group ">
            <%= form.label :url_image, "Poster URL" %>
            <%= form.text_field :url_image, class: "form-control", :required => true  %>
          </div>
          <div class="form-group">
            <%= form.label :premiere, "Estreno"%>
            <%= form.text_field :premiere, class: "form-control", :required => true  %>
          </div>
          <div class="form-group">
            <%= form.label :dayshow, "Días de Presentación"%>
            <%= form.number_field :dayshow, id: :movie_dayshow, value:1, min:1, class: "form-control", :required => true %>
          </div>
      </div>
      <div class="modal-footer">
        <div class="actions">
          <%= form.submit "Crear Nueva Pélicula", class: "btn btn-info btncustom float-right" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>
  <script type="text/javascript">
    var tzoffset = (new Date()).getTimezoneOffset() * 60000;
    var localISOTime = new Date(Date.now() - tzoffset)
    var todayDate = localISOTime.toISOString().slice(0,10).replace("-","/").replace("-","/");
    var url1 ='/moviesdash.json';
    var vueapp = new Vue({
      el: '#vueapp',
      created: function(){
        this.getAga();
      },
      data:{
        lists:[]
      },
      methods:{
        getAga: function(){
          fechainit=document.getElementById("dateshowprac").value
          axios.get(url1+"?date="+fechainit).then(response=>{
            this.lists=response.data
          });
        },
        asignarmovieid: function(id){
          document.getElementById('day_id').value=id;
        }
      }
    })
  </script>

app/views/movies/new.html.erb
<%= render 'form', movie: @movie %>

app/views/movies/show.html.erb
<p>
  <strong>Título:</strong>
  <%= @movie.name %>
</p>

<p>
  <strong>Sinopsis:</strong>
  <%= @movie.description %>
</p>

<p>
  <strong>Poster:</strong>
  <img src="<%= @movie.url_image %>" alt="Avatar" class="image">

</p>

<p>
  <strong>Funciones:</strong>
  <% @movie.days.each do |day| %>
    <%= day.dateShow %> <br>
  <% end %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

app/views/reservations/_form.html.erb
<%= form_with(model: reservation, local: true) do |form| %>
  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :nid %>
    <%= form.text_field :nid %>
  </div>

  <div class="field">
    <%= form.label :movie_id %>
    <%= form.text_field :movie_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<link rel="stylesheet" type="text/css" href="/assets/jquery.dataTables.min.css">
<script type="text/javascript" charset="utf8" src="/assets/jquery.dataTables.min.js"></script>
<div class="box box-default">
  <div class="box-header">
    <h1> Reservas Realizadas</h1>
  </div>
  <div class="box-body">
    <table  id="grid" class="grid table dt-responsive">
        <thead>
          <tr>
            <th>Película</th>
            <th>Día</th>
            <th>Cédula</th>
            <th>Nombre</th>
            <th>correo Eléctronico</th>
            <th>Celular</th>
          </tr>
        </thead>

        <tbody>
          <% @reservations.each do |reserf| %>
            <tr>
              <td><%= reserf.day.movie.name %></td>
              <td><%= reserf.day.dateShow %></td>
              <td><%= reserf.nid %></td>
              <td><%= reserf.name %></td>
              <td><%= reserf.email %></td>
              <td><%= reserf.phone %></td>
            </tr>
          <% end %>
        </tbody>
    </table>
  </div>
</div>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @reservation.name %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @reservation.phone %>
</p>

<p>
  <strong>Correo Eléctronico:</strong>
  <%= @reservation.email %>
</p>



<p>
  <strong>Cédula:</strong>
  <%= @reservation.nid %>
</p>

<p>
  <strong>Día:</strong>
  <%= @reservation.day.dateShow %>
</p>


<p>
  <strong>Movie:</strong>
  <%= @reservation.day.movie.name %>
    <img src="<%= @reservation.day.movie.url_image %>" alt="Avatar" class="image">

</p>